sudo: required
language: python

services:
  - docker
before_install:
  - docker build -t lukasheinrich/testcmakeatlas .
script:
  - docker run -it lukasheinrich/testcmakeatlas  /bin/bash -c 'source ./setup.sh'

